<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Tggl</PackageId>
    <Version>1.1.4</Version>
    <Authors>Nicolas Keller</Authors>
    <Description>Tggl .NET SDK</Description>
    <TargetFrameworks>net6.0;net7.0;net8.0</TargetFrameworks>
    <PackageTags>featureflags feature flags sdk tggl</PackageTags>
        <PackageProjectUrl>https://tggl.io/</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Tggl/dotnet-tggl-client</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Hashing" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="obj\" />
    <None Include="README.md" Pack="true" PackagePath="\"/>
  </ItemGroup>

</Project>
